### ISSUE TITLE
PHP warning on log_moderator_action()

### ISSUE THREAD

**Issue by Sama34** [JN-Jones/Wiki#1]
Because log_moderator_action() expects _$data_ to be an array with the 'fid' and 'tid' keys, the wiki show a PHP warning when running this function.

**Comment by JN-Jones** [comment]
First: this plugin is abandoned so I'll close this anyway.
But I also think this is more an issue with mybb than with the plugin. As far as I've seen it mybb checks in log_moderator_action whether fid and tid are an empty string. Instead we should use isset and empty there
